export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/auth/login',
    REGISTER: '/auth/register',
    VERIFY_OTP: '/auth/verify-otp',
    RESEND_OTP: '/auth/resend-otp',
    LOGOUT: '/auth/logout',
    PROFILE: '/auth/profile',
    REFRESH_TOKEN: '/auth/refresh-token',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: '/auth/reset-password',
  },
  ADMIN: {
    REGISTER: '/admins/register',
    PROFILE: '/admins/profile',
    STATS: '/admins/stats',
    USERS: '/admins/users',
    ROLES: '/admins/roles',
    LEAVES: '/admins/leaves',
  },
  STUDENTS: {
    BASE: '/students',
    REGISTER: '/students/register',
    LOGIN: '/students/login',
    ALUMNI: '/students/alumni',
    PROMOTE: '/students/promote-to-alumni',
    ENROLL: '/students/enroll',
    ENROLLMENT_HISTORY: (id) => `/students/enrollment-history/${id}`,
    LEAVE: '/students/leave',
    LEAVE_HISTORY: (id) => `/students/leave/${id}`,
  },
  TEACHERS: {
    BASE: '/faculties',
    REGISTER: '/faculties/register',
    LOGIN: '/faculties/login',
    LEAVE: '/faculties/leave',
    LEAVE_HISTORY: (id) => `/faculties/leave/${id}`,
    ALLOCATE_SUBJECT: '/faculties/allocate-subject',
    SCHEDULES: (id) => `/faculties/schedules/${id}`,
    STAFF: '/faculties/staff',
  },
  COURSES: {
    BASE: '/courses',
    ASSIGNMENTS: '/courses/assignments',
    HOMEWORKS: '/courses/homeworks',
    BATCHES: '/courses/batches',
    CLASSES: '/courses/classes',
    SECTIONS: '/courses/sections',
    SUBJECTS: '/courses/subjects',
    TIMETABLE: '/courses/timetable',
  },
  ATTENDANCE: {
    RECORD: '/attendance/record',
    STUDENT: '/attendance/student',
    COURSE: '/attendance/course',
    UPDATE: '/attendance/update',
  },
  EXAMS: {
    SCHEDULES: '/exams/schedules',
  },
  RESULTS: {
    BASE: '/results',
    GRADING: '/results/grading-scale',
    CERTIFICATE: '/results/certificate',
    MARKS: '/results/marks',
    STUDENT: (id) => `/results/student/${id}`,
  },
  FEES: {
    BASE: '/fees',
    STUDENT: (id) => `/fees/student/${id}`,
    PAYMENT: '/fees/payment',
    INVOICE: (id) => `/fees/invoice/${id}`,
    RECORD_PAYMENT: '/fees/record-payment',
  },
  COMMUNICATION: {
    COMPLAINTS: '/communication/complaints',
    COMPLAINT_RESOLVE: (id) => `/communication/complaints/${id}/resolve`,
    EVENTS: '/communication/events',
    NOTICES: '/communication/notices',
    NOTIFICATIONS: '/communication/notifications',
  },
  DASHBOARD: {
    STATS: '/dashboard',
  },
  SETTINGS: {
    BASE: '/settings',
  },
};
